import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./SessionWrapper";
import { Toaster } from "sonner";

const raleway = Raleway({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: any;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <body className={`${raleway.className} antialiased`}>
        <Toaster richColors />
        <SessionWrapper session={session}>{children}</SessionWrapper>
      </body>
    </html>
  );
}
